export type EmailTemplateCategory =
  | 'Access and onboarding'
  | 'Learning and engagement'
  | 'Assignments and events'
  | 'Achievements'
  | 'Payments and subscriptions';

export type EmailTemplateDefinition = {
  key: string;
  label: string;
  category: EmailTemplateCategory;
  description: string;
  schedule: string;
  defaultSubject: string;
  defaultBody: string;
  tags: string[];
  requiredTags: string[];
  ctaLabel?: string;
};

const d = (definition: EmailTemplateDefinition) => definition;

export const EMAIL_TEMPLATE_DEFINITIONS = [
  d({ key: 'account_setup', label: 'Account setup', category: 'Access and onboarding', description: 'Sent when a learner account is created and needs a password.', schedule: 'Immediately after account creation', defaultSubject: 'Your {{app_name}} account is ready', defaultBody: '<p>Hi {{student_name}},</p><p>Your learning account is ready. Use the secure button below to set your password and sign in.</p>', tags: ['student_name', 'app_name'], requiredTags: ['student_name'], ctaLabel: 'Set Password' }),
  d({ key: 'cohort_invite', label: 'Cohort invitation', category: 'Access and onboarding', description: 'Sent to an email address invited to join a cohort.', schedule: 'When an invitation is created', defaultSubject: 'You have been invited to join {{app_name}}', defaultBody: '<p>Hi {{student_name}},</p><p>You have been invited to join {{cohort_name}} on {{app_name}}.</p>', tags: ['student_name', 'cohort_name', 'app_name'], requiredTags: ['cohort_name'], ctaLabel: 'Accept Invitation' }),
  d({ key: 'cohort_added', label: 'Added to cohort', category: 'Access and onboarding', description: 'Sent to an existing learner added to a cohort.', schedule: 'When an existing learner is admitted', defaultSubject: 'You have been added to {{cohort_name}}', defaultBody: '<p>Hi {{student_name}},</p><p>You have been added to {{cohort_name}}. Sign in to see the learning available to you.</p>', tags: ['student_name', 'cohort_name', 'app_name'], requiredTags: ['cohort_name'], ctaLabel: 'Sign In' }),
  d({ key: 'individual_learner_welcome', label: 'Subscription learner welcome', category: 'Access and onboarding', description: 'Combines account setup and subscription access for a new learner.', schedule: 'When staff enrolls a new subscription learner', defaultSubject: 'Your {{app_name}} account is ready', defaultBody: '<p>Hi {{student_name}},</p><p>Your account and {{plan_name}} access are ready. Set your password to begin.</p>', tags: ['student_name', 'app_name', 'plan_name', 'period_end'], requiredTags: ['student_name', 'plan_name'], ctaLabel: 'Set Password' }),
  d({ key: 'onboarding_welcome', label: 'Onboarding welcome', category: 'Access and onboarding', description: 'Welcomes a learner after onboarding.', schedule: 'Immediately after onboarding', defaultSubject: 'Welcome to {{app_name}}, {{student_name}}!', defaultBody: '<p>Hi {{student_name}},</p><p>Welcome to {{app_name}}. Your learning dashboard is ready.</p>', tags: ['student_name', 'app_name'], requiredTags: ['student_name'], ctaLabel: 'Open Dashboard' }),
  d({ key: 'onboarding_day3', label: 'Day 3 check-in', category: 'Access and onboarding', description: 'Checks in shortly after onboarding.', schedule: '3 days after onboarding', defaultSubject: '{{student_name}}, your courses are waiting for you', defaultBody: '<p>Hi {{student_name}},</p><p>Your learning is ready when you are. Continue with {{content_title}} or open your dashboard.</p>', tags: ['student_name', 'content_title', 'app_name'], requiredTags: ['student_name'], ctaLabel: 'Continue Learning' }),
  d({ key: 'onboarding_day7', label: 'Day 7 encouragement', category: 'Access and onboarding', description: 'Encourages progress one week after onboarding.', schedule: '7 days after onboarding', defaultSubject: 'Keep going, {{student_name}}', defaultBody: '<p>Hi {{student_name}},</p><p>You have completed {{completed_count}} course items so far. Keep building your momentum.</p>', tags: ['student_name', 'completed_count', 'app_name'], requiredTags: ['student_name'], ctaLabel: 'Continue Learning' }),
  d({ key: 'group_assigned', label: 'Added to group', category: 'Access and onboarding', description: 'Tells a learner they were added to a learning group.', schedule: 'When group membership is assigned', defaultSubject: 'You have been added to {{group_name}}', defaultBody: '<p>Hi {{student_name}},</p><p>You are now a member of {{group_name}} in {{cohort_name}}.</p>', tags: ['student_name', 'group_name', 'cohort_name'], requiredTags: ['group_name'], ctaLabel: 'Open Dashboard' }),
  d({ key: 'content_assigned', label: 'Content assigned', category: 'Learning and engagement', description: 'Covers assigned courses, events, virtual experiences, assignments and certifications.', schedule: 'When content is assigned or added through a plan', defaultSubject: 'You have been assigned: {{content_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>A new {{content_type}} is available to you: <strong>{{content_title}}</strong>.</p>', tags: ['student_name', 'content_title', 'content_type', 'app_name'], requiredTags: ['content_title'], ctaLabel: 'Open Content' }),
  d({ key: 'learning_path_assigned', label: 'Learning path assigned', category: 'Learning and engagement', description: 'Sent when a learning path becomes available.', schedule: 'When a learning path is assigned', defaultSubject: 'You have been enrolled in a new learning path: {{path_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>Your new learning path, <strong>{{path_title}}</strong>, is ready.</p>', tags: ['student_name', 'path_title', 'app_name'], requiredTags: ['path_title'], ctaLabel: 'View Learning Path' }),
  d({ key: 'next_learning_item', label: 'Next learning item', category: 'Learning and engagement', description: 'Points the learner to the next item in a path.', schedule: 'After completing a path item', defaultSubject: 'Next up in {{path_title}}: {{content_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>Great work. Your next item in {{path_title}} is <strong>{{content_title}}</strong>.</p>', tags: ['student_name', 'path_title', 'content_title'], requiredTags: ['path_title', 'content_title'], ctaLabel: 'Continue Learning' }),
  d({ key: 'weekly_digest', label: 'Weekly learning update', category: 'Learning and engagement', description: 'Summarizes completed, active, overdue and not-started learning.', schedule: 'Every Monday at 08:00', defaultSubject: 'Your weekly learning update', defaultBody: '<p>Hi {{student_name}},</p><p>Here is your weekly update: {{completed_count}} completed, {{in_progress_count}} in progress, {{not_started_count}} not started and {{overdue_count}} overdue.</p>', tags: ['student_name', 'completed_count', 'in_progress_count', 'not_started_count', 'overdue_count'], requiredTags: ['student_name', 'completed_count', 'in_progress_count', 'not_started_count', 'overdue_count'], ctaLabel: 'Open Dashboard' }),
  d({ key: 'inactivity_nudge', label: 'Inactivity reminder', category: 'Learning and engagement', description: 'Encourages a learner to return to stalled work.', schedule: 'After 7 days without progress, with a cooldown', defaultSubject: 'We miss you, {{student_name}}. Come back and keep learning', defaultBody: '<p>Hi {{student_name}},</p><p>You made a start on <strong>{{content_title}}</strong>. Come back and continue where you stopped.</p>', tags: ['student_name', 'content_title', 'content_type'], requiredTags: ['content_title'], ctaLabel: 'Continue Learning' }),
  d({ key: 'deadline_reminder', label: 'Content deadline reminder', category: 'Learning and engagement', description: 'Warns about a course, event or virtual experience deadline.', schedule: 'Daily, normally from 3 days before the deadline', defaultSubject: 'Reminder: {{content_title}} is due {{due_text}}', defaultBody: '<p>Hi {{student_name}},</p><p><strong>{{content_title}}</strong> is due {{due_text}}.</p>', tags: ['student_name', 'content_title', 'content_type', 'due_text'], requiredTags: ['content_title', 'due_text'], ctaLabel: 'Open Content' }),
  d({ key: 've_milestone', label: 'Virtual experience milestone', category: 'Learning and engagement', description: 'Encourages a learner who reaches 80 percent progress.', schedule: 'Once at 80 percent completion', defaultSubject: 'You are 80% done. Finish strong!', defaultBody: '<p>Hi {{student_name}},</p><p>You are close to completing <strong>{{content_title}}</strong>. Keep going.</p>', tags: ['student_name', 'content_title'], requiredTags: ['content_title'], ctaLabel: 'Finish Experience' }),
  d({ key: 've_reviewed', label: 'Instructor review ready', category: 'Learning and engagement', description: 'Tells a learner their virtual experience work was reviewed.', schedule: 'When a meaningful review is saved', defaultSubject: 'Your instructor reviewed your work: {{content_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>Your instructor reviewed <strong>{{content_title}}</strong>. Your score is {{score}}/100.</p>', tags: ['student_name', 'content_title', 'score', 'feedback'], requiredTags: ['content_title', 'score'], ctaLabel: 'View Review' }),
  d({ key: 'assignment_due', label: 'Assignment due reminder', category: 'Assignments and events', description: 'Reminds learners who have not submitted an assignment.', schedule: 'Daily for assignments due within 2 days', defaultSubject: 'Reminder: {{assignment_title}} is due {{due_text}}', defaultBody: '<p>Hi {{student_name}},</p><p>Your assignment <strong>{{assignment_title}}</strong> is due {{due_text}}.</p>', tags: ['student_name', 'assignment_title', 'due_date', 'due_text'], requiredTags: ['assignment_title', 'due_text'], ctaLabel: 'View Assignment' }),
  d({ key: 'submission_received', label: 'Submission received', category: 'Assignments and events', description: 'Confirms an individual or virtual experience assignment submission.', schedule: 'Immediately after submission', defaultSubject: 'Submission received: {{assignment_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>We received your submission for <strong>{{assignment_title}}</strong>.</p>', tags: ['student_name', 'assignment_title'], requiredTags: ['assignment_title'], ctaLabel: 'View Assignments' }),
  d({ key: 'group_submission_received', label: 'Group submission received', category: 'Assignments and events', description: 'Confirms a group assignment submission to group members.', schedule: 'Immediately after group submission', defaultSubject: 'Group submission received: {{assignment_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>{{submitted_by}} submitted <strong>{{assignment_title}}</strong> for {{group_name}}.</p>', tags: ['student_name', 'submitted_by', 'assignment_title', 'group_name'], requiredTags: ['assignment_title', 'group_name'], ctaLabel: 'View Assignment' }),
  d({ key: 'assignment_graded', label: 'Assignment graded', category: 'Assignments and events', description: 'Tells learners their assignment was graded.', schedule: 'When an instructor saves a grade', defaultSubject: 'Your assignment has been graded: {{assignment_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>Your score for <strong>{{assignment_title}}</strong> is {{score}}/100.</p>', tags: ['student_name', 'assignment_title', 'score', 'feedback'], requiredTags: ['assignment_title', 'score'], ctaLabel: 'View Result' }),
  d({ key: 'event_confirmation', label: 'Event registration confirmation', category: 'Assignments and events', description: 'Confirms an event registration or automatic cohort registration.', schedule: 'Immediately after registration', defaultSubject: 'You are registered: {{event_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>You are registered for <strong>{{event_title}}</strong>.</p><p><strong>When:</strong> {{event_time_display}}<br><strong>Where:</strong> {{event_location}}</p>', tags: ['student_name', 'event_title', 'event_time_display', 'event_location'], requiredTags: ['event_title', 'event_time_display', 'event_location'], ctaLabel: 'View Event' }),
  d({ key: 'event_reminder', label: 'Event reminder', category: 'Assignments and events', description: 'Reminds registered learners about an upcoming event.', schedule: 'One day or one hour before the event', defaultSubject: 'Reminder: {{event_title}} starts {{reminder_timing}}', defaultBody: '<p>Hi {{student_name}},</p><p><strong>{{event_title}}</strong> starts {{reminder_timing}}.</p><p><strong>When:</strong> {{event_time_display}}<br><strong>Where:</strong> {{event_location}}</p>', tags: ['student_name', 'event_title', 'reminder_timing', 'event_time_display', 'event_location'], requiredTags: ['event_title', 'reminder_timing', 'event_time_display', 'event_location'], ctaLabel: 'View Event' }),
  d({ key: 'missed_event', label: 'Missed session follow-up', category: 'Assignments and events', description: 'Follows up with learners absent from a live session.', schedule: 'When an instructor nudges absent learners', defaultSubject: 'We missed you at {{event_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>We missed you at <strong>{{event_title}}</strong>. Open your dashboard for the next steps and available resources.</p>', tags: ['student_name', 'event_title', 'event_date'], requiredTags: ['event_title'], ctaLabel: 'Open Dashboard' }),
  d({ key: 'recording_published', label: 'Recording published', category: 'Assignments and events', description: 'Tells learners that new session recordings are available.', schedule: 'When new recording weeks are published', defaultSubject: 'New recordings available: {{recording_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>New recordings for <strong>{{recording_title}}</strong> are available.</p>', tags: ['student_name', 'recording_title', 'weeks'], requiredTags: ['recording_title'], ctaLabel: 'Watch Recordings' }),
  d({ key: 'course_certificate', label: 'Course or certification certificate', category: 'Achievements', description: 'Delivers a certificate after a qualifying course, certification or virtual experience completion.', schedule: 'After a qualifying completion', defaultSubject: 'Your certificate for {{content_title}} is ready', defaultBody: '<p>Hi {{student_name}},</p><p>Congratulations on completing <strong>{{content_title}}</strong>. Your certificate is ready.</p>', tags: ['student_name', 'content_title'], requiredTags: ['content_title'], ctaLabel: 'View Certificate' }),
  d({ key: 'course_result', label: 'Course result without certificate', category: 'Achievements', description: 'Shares a course or virtual experience result when no certificate was earned.', schedule: 'After a non-passing completion', defaultSubject: 'Your result for {{content_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>Your result for <strong>{{content_title}}</strong> is {{score}}%. Review your result and try again when you are ready.</p>', tags: ['student_name', 'content_title', 'score'], requiredTags: ['content_title', 'score'], ctaLabel: 'View Result' }),
  d({ key: 'learning_path_certificate', label: 'Learning path certificate', category: 'Achievements', description: 'Delivers a certificate for a completed learning path.', schedule: 'After completing every path item', defaultSubject: 'Your Learning Path Certificate is ready: {{path_title}}', defaultBody: '<p>Hi {{student_name}},</p><p>Congratulations on completing <strong>{{path_title}}</strong>. Your certificate is ready.</p>', tags: ['student_name', 'path_title'], requiredTags: ['path_title'], ctaLabel: 'View Certificate' }),
  d({ key: 'open_certificate', label: 'Open certificate', category: 'Achievements', description: 'Delivers a certificate issued outside a course attempt.', schedule: 'When an open certificate is issued', defaultSubject: 'Your {{program_name}} Certificate', defaultBody: '<p>Hi {{student_name}},</p><p>Your certificate for <strong>{{program_name}}</strong> is ready.</p>', tags: ['student_name', 'program_name'], requiredTags: ['program_name'], ctaLabel: 'View Certificate' }),
  d({ key: 'payment_receipt', label: 'Payment receipt', category: 'Payments and subscriptions', description: 'Confirms a payment recorded on the learner account.', schedule: 'Immediately after payment is recorded', defaultSubject: 'Payment received on your account', defaultBody: '<p>Hi {{student_name}},</p><p>We received your payment of <strong>{{currency}} {{amount}}</strong>.</p>', tags: ['student_name', 'currency', 'amount'], requiredTags: ['currency', 'amount'] }),
  d({ key: 'payment_confirmation_received', label: 'Payment confirmation received', category: 'Payments and subscriptions', description: 'Acknowledges a learner-submitted payment confirmation.', schedule: 'Immediately after confirmation is submitted', defaultSubject: 'We received your payment confirmation', defaultBody: '<p>Hi {{student_name}},</p><p>We received your confirmation for <strong>{{currency}} {{amount}}</strong>. The team will review it.</p>', tags: ['student_name', 'currency', 'amount'], requiredTags: ['currency', 'amount'], ctaLabel: 'Open Payments' }),
  d({ key: 'payment_confirmation_approved', label: 'Payment confirmation approved', category: 'Payments and subscriptions', description: 'Confirms that staff approved a payment confirmation.', schedule: 'When staff approves confirmation', defaultSubject: 'Your payment confirmation has been approved', defaultBody: '<p>Hi {{student_name}},</p><p>Your payment confirmation for <strong>{{currency}} {{amount}}</strong> was approved.</p>', tags: ['student_name', 'currency', 'amount', 'admin_notes'], requiredTags: ['currency', 'amount'], ctaLabel: 'Open Dashboard' }),
  d({ key: 'payment_confirmation_rejected', label: 'Payment confirmation not verified', category: 'Payments and subscriptions', description: 'Explains that a payment confirmation could not be verified.', schedule: 'When staff rejects confirmation', defaultSubject: 'Your payment confirmation could not be verified', defaultBody: '<p>Hi {{student_name}},</p><p>We could not verify the payment confirmation for <strong>{{currency}} {{amount}}</strong>. Please review the details and upload clear proof of payment. {{admin_notes}}</p>', tags: ['student_name', 'currency', 'amount', 'admin_notes'], requiredTags: ['currency', 'amount'], ctaLabel: 'Review Payment' }),
  d({ key: 'payment_request', label: 'Subscription payment request', category: 'Payments and subscriptions', description: 'Asks an existing learner to pay for assigned subscription access.', schedule: 'When staff creates a payment request', defaultSubject: 'Payment request for {{plan_name}}', defaultBody: '<p>Hi {{student_name}},</p><p>A payment of <strong>{{currency}} {{amount}}</strong> is requested for {{plan_name}}. Review the request in your dashboard for the due date and payment details.</p>', tags: ['student_name', 'plan_name', 'currency', 'amount'], requiredTags: ['plan_name', 'currency', 'amount'], ctaLabel: 'Review Payment' }),
  d({ key: 'subscription_activated', label: 'Subscription activated or extended', category: 'Payments and subscriptions', description: 'Confirms plan access after activation or renewal.', schedule: 'After subscription payment is processed', defaultSubject: 'Your {{plan_name}} subscription is active', defaultBody: '<p>Hi {{student_name}},</p><p>Your {{plan_name}} access is active until {{period_end}}.</p>', tags: ['student_name', 'plan_name', 'period_start', 'period_end', 'duration_months'], requiredTags: ['plan_name', 'period_end'], ctaLabel: 'Start Learning' }),
  d({ key: 'subscription_expiring', label: 'Subscription expiring', category: 'Payments and subscriptions', description: 'Warns before subscription access expires.', schedule: 'Once within 7 days of period end', defaultSubject: 'Your {{plan_name}} access ends soon', defaultBody: '<p>Hi {{student_name}},</p><p>Your {{plan_name}} access ends on {{period_end}} ({{days_left}} days remaining).</p>', tags: ['student_name', 'plan_name', 'period_end', 'days_left'], requiredTags: ['plan_name', 'period_end'], ctaLabel: 'Review Subscription' }),
  d({ key: 'grace_period', label: 'Payment grace period', category: 'Payments and subscriptions', description: 'Warns when a grace period starts and one day before it ends.', schedule: 'At grace-period start and one day before expiry', defaultSubject: 'Your payment is overdue', defaultBody: '<p>Hi {{student_name}},</p><p>Your payment is overdue. Your grace period ends on {{grace_end_date}}.</p>', tags: ['student_name', 'grace_end_date', 'days_left'], requiredTags: ['grace_end_date'], ctaLabel: 'Review Payment' }),
  d({ key: 'overdue_payment', label: 'Overdue payment', category: 'Payments and subscriptions', description: 'Warns that a learner account has an overdue balance.', schedule: 'During the outstanding-payment sweep or a manual reminder', defaultSubject: 'Your account has an overdue payment', defaultBody: '<p>Hi {{student_name}},</p><p>Your account has an overdue payment. Review your balance and payment options.</p>', tags: ['student_name'], requiredTags: [], ctaLabel: 'Review Payment' }),
  d({ key: 'abandoned_checkout', label: 'Abandoned checkout reminder', category: 'Payments and subscriptions', description: 'Reminds a learner about a checkout they started but did not finish.', schedule: 'About 1 hour, 1 day and 3 days after checkout', defaultSubject: 'Still interested in {{plan_name}}?', defaultBody: '<p>Hi {{student_name}},</p><p>You started subscribing to <strong>{{plan_name}}</strong> for {{currency}} {{amount}} but did not finish. Nothing has been charged.</p>', tags: ['student_name', 'plan_name', 'currency', 'amount', 'duration'], requiredTags: ['plan_name', 'currency', 'amount'], ctaLabel: 'Finish Payment' }),
] as const;

export type EmailTemplateKey = typeof EMAIL_TEMPLATE_DEFINITIONS[number]['key'];

export const EMAIL_TEMPLATE_BY_KEY = new Map<string, EmailTemplateDefinition>(
  EMAIL_TEMPLATE_DEFINITIONS.map(definition => [definition.key, definition]),
);

export function getEmailTemplateDefinition(key: string) {
  return EMAIL_TEMPLATE_BY_KEY.get(key) ?? null;
}
